USE SALESDB;
# QUESTION ONE
SELECT employees.firstname, employees.LASTNAME, employees.EMAIL ,employees.OFFICECODE
FROM employees
INNER JOIN offices
ON employees.OFFICECODE = OFFICES.OFFICECODE;

# question 2

SELECT PRODUCTS.PRODUCTNAME, PRODUCTS.PRODUCTVENDOR, PRODUCTS.PRODUCTLINE
FROM PRODUCTS
LEFT JOIN PRODUCTLINES
ON PRODUCTS.PRODUCTLINE = PRODUCTLINES.PRODUCTLINE;

# QUESTION THREE
SELECT orders.ORDERDATE,orders.SHIPPEDdate, orders.status, orders.customernumber
FROM orders
RIGHT JOIN CUSTOMERS
ON CUSTOMERS.CUSTOMERNUMBER = ORDERS.CUSTOMERNUMBER
LIMIT 10;
